config/routes.rb
ImageApp::Application.routes.draw do
  resources :paintings

  

end

app/models/painting.rb
class Painting < ActiveRecord::Base
	validates_presence_of :name
  after_update :crop_image
	# before_create :default_name
  # attr_accessible :gallery_id, :name, :image
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :stored_image
  # belongs_to :gallery
  mount_uploader :image, ImageUploader

  def crop_image
    image.recreate_versions! if crop_x.present?
  end
# To be used for jquery multi file uploader:
	def default_name
	  self.name ||= File.basename(image.filename, '.*').titleize if image
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        if params[:painting][:image].present? || params[:painting][:remote_image_url].present? || params[:painting][:stored_image].present?
          format.html { render :crop }
        else
          format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
          format.json { render action: 'show', status: :created, location: @painting }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        if params[:painting][:image].present? || params[:painting][:remote_image_url].present? || params[:painting][:stored_image].present?
          format.html { render :crop }
        else
          format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: 'edit' }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:name, :image, :remote_image_url, :stored_image, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/_crop.slim
h1 Crop Image
= image_tag @painting.image_url(:large), id: "cropbox"

h4 Preview
div style="width:100px; height:100px; overflow:hidden;"
	= image_tag @painting.image.url(:large), :id => "preview"

= form_for @painting do |f|
  .actions
  	- %w[x y w h].each do |attribute| 
    	= f.hidden_field "crop_#{attribute}"
    = f.submit "Crop"

app/views/paintings/_form.html.slim
= form_for @painting, :html => {:multipart => true} do |f|
  / = f.error_messages
  / = f.hidden_field :gallery_id

  - if @painting.errors.any?
    #error_explanation
      h2 = "#{pluralize(@painting.errors.count, "error")} prohibited this painting from being saved:"
      ul
        - @painting.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
    = f.label :remote_image_url, "Image URL:"
    = f.text_field :remote_image_url
    = f.hidden_field :stored_image,:value=>("a" unless @painting.new_record?)
    = f.label :image, "Or upload an image:"
    = f.file_field :image
    = f.hidden_field :image_cache
    label
      = f.check_box :remove_image
    
  .actions = f.submit 'Save'

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#paintings").append("<%= j render(@painting) %>");
<% end %>

app/views/paintings/crop.slim
h1 Crop Image
= image_tag @painting.image_url(:large), id: "cropbox"

h4 Preview
div style="width:100px; height:100px; overflow:hidden;"
	= image_tag @painting.image.url(:large), :id => "preview"

= form_for @painting do |f|
  .actions
  	- %w[x y w h].each do |attribute| 
    	= f.hidden_field "crop_#{attribute}"
    = f.submit "Crop"

app/views/paintings/edit.html.slim
h1 Editing painting

== render 'crop'
== render 'form'


= link_to 'Show', @painting
'|
= link_to 'Back', paintings_path

app/views/paintings/index.html.slim
h1 Listing paintings

table
  tr
    th Name
    th
    th
    th

  - @paintings.each do |painting|
    tr
      td = image_tag(painting.image_url :mini )
      td = painting.name
      td = link_to 'Show', painting
      td = link_to 'Edit', edit_painting_path(painting)
      td = link_to 'Destroy', painting, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Painting', new_painting_path

/ Below code is from failed jquery multi uploader
/ = form_for Painting.new do |f| 
  = f.label :image, "Upload paintings:" 
  = f.file_field :image, multiple: true, name: "painting[image]" 

/ script#template-upload type="text/x-tmpl"
/ .upload
  {%=o.name%}
  .progress
    .bar style="width: 0%"

app/views/paintings/new.html.slim
h1 New painting

== render 'form'

= link_to 'Back', paintings_path

app/views/paintings/show.html.slim
p#notice = notice

p
  strong Name:
  = @painting.name


  = image_tag @painting.image_url(:cropped).to_s
  / = image_tag @painting.image_url(:thumb).to_s

= link_to 'Edit', edit_painting_path(@painting)
'|
= link_to 'Back', paintings_path